name: minga_demo
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.0
  bloc: ^7.1.0
  google_fonts: ^1.1.0
  transparent_image: ^1.0.0
  autocomplete_textfield: ^1.7.3
  turf: ^0.0.2+3
  equatable: ^2.0.3
  flutter_localizations:
    sdk: flutter
  async: ^2.4.2
  minga_shared:
    path: ../minga_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  dartclub_lint: any
  intl_translation: ^0.17.10+1
  grinder: ^0.8.6
  translation_service:
    path: /Users/lukashimsel/Projects/minga-app/translation_service

dependency_overrides:
  intl: ^0.17.0

flutter:
  uses-material-design: true
  assets: 
    - assets/